### ISSUE TITLE
Private variable generatorId in abstract Data and Task generators

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/core#27]
I propose to make it protected in order to reuse in user code (e.g. to name loggers or split big dataset) in case if several instances are used.

**Comment by MichaelRoeder** [comment]
The [DataGenerator](https://github.com/hobbit-project/core/blob/master/src/main/java/org/hobbit/core/components/AbstractDataGenerator.java#L107) as well as the [TaskGenerator](https://github.com/hobbit-project/core/blob/master/src/main/java/org/hobbit/core/components/AbstractTaskGenerator.java#L257) offer a `getGeneratorId()` method that can be used for that.

**Comment by smirnp** [comment]
you are right, my fault:)
